name: Sync Fork
 
on:
  schedule:
    - cron: "0 */23 * * *"  # 每23小时执行一次
  workflow_dispatch:       # 允许手动触发
 
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main  # 指定你要更新的分支名
      
      - name: Sync fork with upstream repository
        uses: aorumbayev/sync-with-upstream-action@v1.1.0
        with:
          upstream-branch: main  # 上游仓库的分支名，通常是main或master
          target-branch: main  # 你的分支名
          github-token: ${{ secrets.GITHUB_TOKEN }}
